### ISSUE TITLE
部分alicpp数据文件问题

### ISSUE THREAD

**Issue by JJplane** [qwerfdsaplking/SATrans#1]
norm_data_path = '/mnt/workspace/data/data_norm_{}.csv'
train_acc_feat = load_pkl('/mnt/workspace/work/history/%s_%s_unmapped.pkl' % (col, name))，
请问aliccp_dataset_processing.py里这两个文件是怎么来的呢，这个预处理代码暂时没法直接运行

**Comment by qwerfdsaplking** [comment]
The preprocessed datasets have been uploaded.

**Comment by JJplane** [comment]
可以正常运行了，谢谢~

**Comment by cywuuuu** [comment]
> 可以正常运行了，谢谢~

```
FileNotFoundError: [Errno 2] No such file or directory: '/home/featurize/work/history/109_14_train_unmapped.pkl'
```
请问这个是怎么解决的呢，我也遇到了类似的问题，求问
